SELECT C.TABLE_SCHEMA, 
	   C.TABLE_Name, 
	   C.COLUMN_NAME, 
	   C.DATA_TYPE, 
	   CAST(CASE WHEN C.IS_NULLABLE = 'YES' THEN 1 ELSE 0 END AS bit) AS IS_NULLABLE, 
	   C.CHARACTER_MAXIMUM_LENGTH, 
	   C.COLUMN_DEFAULT, 
	   CAST(CASE WHEN PK.CONSTRAINT_NAME IS NULL THEN 0 ELSE 1 END AS bit) AS PRIMARY_KEY,
	   TC.TABLE_NAME  AS FOREIGN_TABLE,
	   KCU.COLUMN_NAME AS FOREIGN_KEY
FROM INFORMATION_SCHEMA.COLUMNS C 
LEFT JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE CCU ON 
	   C.TABLE_CATALOG = CCU.TABLE_CATALOG AND 
	   C.TABLE_SCHEMA = CCU.TABLE_SCHEMA AND 
	   C.TABLE_NAME = CCU.TABLE_NAME AND 
	   C.COLUMN_NAME = CCU.COLUMN_NAME 
LEFT JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS PK ON 
	   CCU.TABLE_CATALOG = PK.TABLE_CATALOG AND 
	   CCU.TABLE_SCHEMA = PK.TABLE_SCHEMA AND 
	   CCU.TABLE_NAME = PK.TABLE_NAME AND 
	   CCU.CONSTRAINT_NAME = PK.CONSTRAINT_NAME AND 
	   PK.CONSTRAINT_TYPE = 'PRIMARY KEY'
LEFT JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC1 ON
	   CCU.TABLE_CATALOG = TC1.TABLE_CATALOG AND 
	   CCU.TABLE_SCHEMA = TC1.TABLE_SCHEMA AND 
	   CCU.TABLE_NAME = TC1.TABLE_NAME AND 
	   CCU.CONSTRAINT_NAME = TC1.CONSTRAINT_NAME AND 
	   TC1.CONSTRAINT_TYPE = 'FOREIGN KEY'
LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE FK ON 
	TC1.CONSTRAINT_SCHEMA = FK.CONSTRAINT_SCHEMA AND 
	TC1.CONSTRAINT_NAME = FK.CONSTRAINT_NAME AND
	TC1.CONSTRAINT_TYPE = 'FOREIGN KEY'
LEFT JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS RC ON 
	TC1.CONSTRAINT_SCHEMA = RC.CONSTRAINT_SCHEMA AND 
	TC1.CONSTRAINT_NAME = RC.CONSTRAINT_NAME 
LEFT JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC ON 
	RC.UNIQUE_CONSTRAINT_SCHEMA = TC.CONSTRAINT_SCHEMA AND 
	RC.UNIQUE_CONSTRAINT_NAME = TC.CONSTRAINT_NAME 
LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE KCU ON 
	TC.CONSTRAINT_SCHEMA = KCU.CONSTRAINT_SCHEMA AND 
	TC.CONSTRAINT_NAME = KCU.CONSTRAINT_NAME AND 
	FK.ORDINAL_POSITION = 1
ORDER BY C.TABLE_Name