SELECT C.TABLE_SCHEMA, 
	   C.TABLE_Name, 
	   C.COLUMN_NAME, 
	   C.DATA_TYPE, 
	   CAST(CASE WHEN C.IS_NULLABLE = 'YES' THEN 1 ELSE 0 END AS bit) AS IS_NULLABLE, 
	   C.CHARACTER_MAXIMUM_LENGTH, 
	   C.COLUMN_DEFAULT, 
	   CAST(CASE WHEN PK.CONSTRAINT_NAME IS NULL THEN 0 ELSE 1 END AS bit) AS PRIMARY_KEY,
	   KCU.TABLE_NAME  AS FOREIGN_TABLE,
	   KCU.COLUMN_NAME AS FOREIGN_KEY
FROM INFORMATION_SCHEMA.COLUMNS C 
LEFT JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE CCU ON 
	   C.TABLE_CATALOG = CCU.TABLE_CATALOG AND 
	   C.TABLE_SCHEMA = CCU.TABLE_SCHEMA AND 
	   C.TABLE_NAME = CCU.TABLE_NAME AND 
	   C.COLUMN_NAME = CCU.COLUMN_NAME 
LEFT JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS PK ON 
	   CCU.TABLE_CATALOG = PK.TABLE_CATALOG AND 
	   CCU.TABLE_SCHEMA = PK.TABLE_SCHEMA AND 
	   CCU.TABLE_NAME = PK.TABLE_NAME AND 
	   CCU.CONSTRAINT_NAME = PK.CONSTRAINT_NAME AND 
	   PK.CONSTRAINT_TYPE = 'PRIMARY KEY'
LEFT JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS FK ON 
	   CCU.TABLE_CATALOG = FK.TABLE_CATALOG AND 
	   CCU.TABLE_SCHEMA = FK.TABLE_SCHEMA AND 
	   CCU.TABLE_NAME = FK.TABLE_NAME AND 
	   CCU.CONSTRAINT_NAME = FK.CONSTRAINT_NAME AND 
	   FK.CONSTRAINT_TYPE = 'FOREIGN KEY'
LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KCU
    ON KCU.CONSTRAINT_CATALOG = FK.CONSTRAINT_CATALOG
    AND KCU.CONSTRAINT_SCHEMA = FK.CONSTRAINT_SCHEMA 
    AND KCU.CONSTRAINT_NAME = FK.CONSTRAINT_NAME 
    AND KCU.ORDINAL_POSITION = 1
ORDER BY C.TABLE_Name